// {
//   "name": "Product Name Example",
//   "desc": "Product Description Example",
//   "quantity": 10,
//   "categoryId": "category123",
//   "price": 29.99,
//   "discount": 5,
//   "images": ["image1.jpg", "image2.jpg"],
//   "coverPhoto": "cover.jpg",
//   "color": "Blue",
//   "size": "Medium",
//   "condition": "New",
//   "brand": "Brand XYZ",
//   "metaData": ["metadata#1", "metadata#1"],
//   "deliveryLocations": ["USA", "Canada", "UK"],
//   "sold": false,
//   "isOutOfStock": false,
//   "isPromoted": true,
//   "vendorId": "vendor123",
//   "ratings": 4.5,
//   "ratedBy": 1000,
//   "customId": "custom123"
// }

// {
//     "name": "School bag",
// "desc": "A back bag shipped from abroad",
//     "quantity": 10,
//     "price": 450.99,
//     "discount": 10,
//     "color": "Blue",
//     "size": "Medium",
//     "condition": "New",
//     "brand": "Samsung",
//     "deliveryLocations": ["USA", "Canada", "UK"],
//     "sold": false,
//     "isOutOfStock": false,
//     "isPromoted": true,
//     "ratings": 4,
//   }
